### ISSUE TITLE
403 errors on weechat.org/files/src/{,devel} directory listings

### ISSUE THREAD

**Issue by cardi** [weechat/weechat.org#102]
It seems like directory listings are disabled, returning 403s, on:
* https://weechat.org/files/src/
* https://weechat.org/files/src/devel/

The [weechat port](https://github.com/macports/macports-ports/blob/master/irc/weechat/Portfile#L19) uses these URLs to check when a new version is released, and the second URL is linked to on the [development tab](https://weechat.org/download/devel/) in the download section.

Is disabling the directory listings intentional? Not a big issue if it is–I can look into other methods for version checks for MacPorts.

**Comment by flashcode** [comment]
Hi,

Yes the disable of index is intentional, the whole `files/` directory was shown and could lead to some private files exposed publicly, so I disabled it.
I could enable index for `files/src/` only, but anyway I think you should not rely on this index to check if a new version is available.
There are some URLs you can use to check the latest version released (which is exactly done for this, you can fetch URLs to retrieve the info directly), see: https://weechat.org/dev/info/

If that's OK for you, I'll just close this issue.

**Comment by cardi** [comment]
> There are some URLs you can use to check the latest version released (which is exactly done for this, you can fetch URLs to retrieve the info directly), see: https://weechat.org/dev/info/

Did not see this previously–that works for me! Thank you!
